
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://sb.nova-acropole.org.br/";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1NDI0NDEsImV4cCI6MjA1MDExODQ0MX0.V9w2aGKP7mKwOJ7oNjGgCOiErsRsyxfaNHr9OWYDq-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
