name: Espelhar para repositório público

on:
  push:
    branches:
      - release # Aciona quando há push na branch 'release' do privado

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório privado
        uses: actions/checkout@v3

      - name: Configurar Git e empurrar para o repositório público
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote add public https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/NovaAcropoleSulPOA/olimpia-manager-eecc.git
          git push --force public release:main  # Empurra a branch 'release' do privado para a branch 'main' do público
