name: Espelhar release e Deploy

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  mirror-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Puxa o código do privado
      - name: Checkout do repositório privado
        uses: actions/checkout@v3

      # 2) Espelha a branch release no repo público
      - name: Configurar Git e espelhar para o público
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote add public https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/EECC-NA-POA/olimpia-manager-eecc.git
          git push --force public release:release

      # 3) instala Node.js (para build do front)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 4) instala dependências
      - name: Install dependencies
        run: npm ci

      # 5) gera o .env.production com as variáveis do Supabase self-hosted
      - name: Generate .env.production
        run: |
          echo VITE_SUPABASE_URL=${{ secrets.SUPABASE_URL }}     >> .env.production
          echo VITE_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} >> .env.production
          # opcional, se você usar service role key em scripts no front:
          echo VITE_SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} >> .env.production

      # 6) builda o seu app Vite/React
      - name: Build
        run: npm run build

      # 7) faz o deploy pro Lovable
      - name: Deploy to Lovable
        run: npx lovable deploy
